apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: new-project
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
