apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-database
  namespace: new-project
spec:
  selector:
    matchLabels:
      app: postgres-data
  serviceName: db
  template:
    metadata:
      labels:
        app: postgres-data
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_HOST
          value: db
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }} 
        - name: POSTGRES_DB
          value: {{ .Values.postgres.dbName }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data-pv
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data-pv
        persistentVolumeClaim:
          claimName: {{ .Values.postgres.pvcName }}
  
