apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
